In [4]:
import gym
import gym_crumb
from agent.agent_synth import AgentSynth

In [5]:
import matplotlib.pyplot as plt
import os
if os.environ.get("DISPLAY") is str and len(os.environ.get("DISPLAY"))!=0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [7]:
env = gym.make("crumb-synthetic-v0")
agent = AgentSynth(env)
#agent.net.Loadmodel()

In [ ]:
rewards, i = agent.learn(reward=220, max_pathlength=5, n_timesteps=10000)


********** Iteration 1 ************
Rollout
Made rollout
Total number of episodes:                 2242
Average sum of rewards per episode:       -36.67144692239072
Std of rewards per episode:               32.451891657799756
Entropy:                                  -56136.817544489335
KL between old and new distribution:      0.009858984500129649
Surrogate loss:                           205821.82771759902

********** Iteration 2 ************
Rollout
Made rollout
Total number of episodes:                 2230
Average sum of rewards per episode:       -36.91045560538116
Std of rewards per episode:               29.98270839689189
Entropy:                                  -55938.036172638036
KL between old and new distribution:      0.009882911337038093
Surrogate loss:                           203121.2604493793

********** Iteration 3 ************
Rollout
Made rollout
Total number of episodes:                 2240
Average sum of rewards per episode:       -35.226642857142856
Std of re

In [25]:
agent.net.Savemodel()

In [17]:
import numpy as np
rewards = []
s = []
for i in range(10):
    env.state = np.zeros(4)
    reward, steps = agent.play(env)
    rewards.append(reward)
    s.append(steps)
    
rewards, s

1 ) 0.015 (0.10335346766924562, 0.03672565657083604, -0.007972294074666538, 0.09627880325329062, -0.02799412001940948, 0.47108865201491446, -0.05332359503472149, -0.12649362534403563) [-0.02799412  0.47108865 -0.0533236  -0.12649363]
2 ) 0.002999999999999989 (0.07041423408648577, 0.03270433801067951, -9.0370104164168e-05, 0.06235849958517212, -0.0008294846751197987, 0.587082886501024, -0.04372231869720733, -0.15334607056774743) [ 0.02716464  0.11599423  0.00960128 -0.02685245]
3 ) -5 (0.07000151957997074, 0.03329226455663298, -0.0013948657411142176, 0.061562100465793496, -0.0053806327338759355, 0.5938868894263839, -0.03604009553268937, -0.15796291372638235) [-0.00455115  0.006804    0.00768222 -0.00461684]
4 ) 0.0010000000000000009 (0.06937093138578854, 0.03329546645003406, -0.0014616325533279302, 0.06084078948769066, -0.005613589989739015, 0.5974759732735613, -0.03188288312675466, -0.1640633285011661) [-0.00023296  0.00358908  0.00415721 -0.00610041]
5 ) -5 (0.06909288792284449, 0.033

102 ) -5 (0.06820975051451507, 0.03347403878506355, -0.001192847368250448, 0.0594191543849667, -0.004672609261142033, 0.6067703907961337, -0.013822160215553748, -0.19181376896045785) [ 8.10067291e-13  9.26561328e-11  1.93892822e-10 -2.81996232e-10]
103 ) -5 (0.0682097505073265, 0.03347403878797145, -0.001192847368067808, 0.05941915437508012, -0.004672609260457615, 0.6067703908743924, -0.013822160051789312, -0.19181376919863552) [ 6.84417800e-13  7.82587606e-11  1.63764436e-10 -2.38177686e-10]
104 ) -5 (0.06820975050125502, 0.03347403879042754, -0.0011928473679135424, 0.05941915436672987, -0.004672609259879529, 0.6067703909404908, -0.01382215991347191, -0.19181376939980338) [ 5.78086190e-13  6.60983490e-11  1.38317403e-10 -2.01167874e-10]
105 ) -5 (0.06820975049612704, 0.03347403879250199, -0.0011928473677832849, 0.05941915435967722, -0.004672609259391398, 0.606770390996318, -0.013822159796647204, -0.19181376956971224) [ 4.88130369e-13  5.58272040e-11  1.16824706e-10 -1.69908865e-10]
10

253 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751488, 0.05941915432134204, -0.004672609256737743, 0.6067703912997694, -0.013822159161643154, -0.19181377049325704) [ 1.31838984e-16 -1.11022302e-16  4.51028104e-17  4.16333634e-17]
254 ) -5 (0.06820975046825349, 0.033474038803777584, -0.0011928473670751666, 0.05941915432134205, -0.004672609256737806, 0.6067703912997693, -0.013822159161643179, -0.19181377049325715) [-6.24500451e-17 -8.32667268e-17 -2.42861287e-17 -1.24900090e-16]
255 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075145, 0.05941915432134204, -0.0046726092567377295, 0.6067703912997694, -0.01382215916164312, -0.1918137704932571) [7.63278329e-17 8.32667268e-17 5.89805982e-17 6.93889390e-17]
256 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075155, 0.05941915432134204, -0.004672609256737764, 0.6067703912997695, -0.013822159161643144, -0.19181377049325704) [-3.46944695e-17  8.32667268e-17 -2.42861287e-17  4.16333634e-17]
257 )

424 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670750753, 0.05941915432134204, -0.004672609256737487, 0.6067703912997695, -0.013822159161643255, -0.19181377049325699) [ 3.53883589e-16  0.00000000e+00 -2.42861287e-17  6.93889390e-17]
425 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752126, 0.05941915432134204, -0.004672609256737965, 0.6067703912997695, -0.013822159161643376, -0.19181377049325704) [-4.78783679e-16  5.55111512e-17 -1.21430643e-16 -6.93889390e-17]
426 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752384, 0.05941915432134204, -0.004672609256738056, 0.6067703912997695, -0.013822159161643248, -0.1918137704932571) [-9.02056208e-17 -5.55111512e-17  1.28369537e-16 -4.16333634e-17]
427 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752007, 0.05941915432134204, -0.004672609256737924, 0.6067703912997694, -0.013822159161643147, -0.1918137704932571) [ 1.31838984e-16 -1.11022302e-16  1.00613962e-16 -1.38777878e-17]
42

560 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751625, 0.059419154321341996, -0.004672609256737792, 0.6067703912997695, -0.013822159161643213, -0.19181377049325726) [ 1.17961196e-16 -1.11022302e-16 -7.97972799e-17 -9.71445147e-17]
561 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752126, 0.05941915432134204, -0.004672609256737965, 0.6067703912997695, -0.013822159161643154, -0.19181377049325715) [-1.73472348e-16  2.77555756e-17  5.89805982e-17  9.71445147e-17]
562 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075155, 0.05941915432134204, -0.004672609256737764, 0.6067703912997694, -0.013822159161643068, -0.1918137704932571) [ 2.01227923e-16 -1.11022302e-16  8.67361738e-17  4.16333634e-17]
563 ) -5 (0.06820975046825345, 0.033474038803777584, -0.0011928473670752124, 0.059419154321341996, -0.004672609256737965, 0.6067703912997694, -0.013822159161643161, -0.1918137704932572) [-2.01227923e-16  2.77555756e-17 -9.36750677e-17 -1.24900090e-1

648 ) -5 (0.06820975046825349, 0.03347403880377764, -0.0011928473670751868, 0.059419154321342024, -0.004672609256737875, 0.6067703912997696, -0.013822159161643172, -0.19181377049325715) [-2.56739074e-16  8.32667268e-17 -7.97972799e-17 -6.93889390e-17]
649 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751328, 0.059419154321341996, -0.004672609256737688, 0.6067703912997695, -0.013822159161643182, -0.1918137704932572) [ 1.87350135e-16 -8.32667268e-17 -1.04083409e-17 -4.16333634e-17]
650 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751983, 0.059419154321341996, -0.004672609256737917, 0.6067703912997695, -0.013822159161643234, -0.1918137704932572) [-2.28983499e-16 -2.77555756e-17 -5.20417043e-17  1.38777878e-17]
651 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751924, 0.059419154321341996, -0.004672609256737896, 0.6067703912997695, -0.013822159161643133, -0.1918137704932572) [2.08166817e-17 0.00000000e+00 1.00613962e-16 1.38777878e-

749 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075133, 0.05941915432134204, -0.004672609256737688, 0.6067703912997695, -0.01382215916164314, -0.1918137704932571) [4.85722573e-17 5.55111512e-17 1.73472348e-17 6.93889390e-17]
750 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751827, 0.05941915432134204, -0.004672609256737861, 0.6067703912997695, -0.013822159161643192, -0.19181377049325715) [-1.73472348e-16  2.77555756e-17 -5.20417043e-17 -4.16333634e-17]
751 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075145, 0.05941915432134204, -0.0046726092567377295, 0.6067703912997695, -0.013822159161643175, -0.19181377049325704) [1.31838984e-16 5.55111512e-17 1.73472348e-17 9.71445147e-17]
752 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751469, 0.05941915432134204, -0.004672609256737736, 0.6067703912997694, -0.013822159161643116, -0.19181377049325704) [-6.93889390e-18 -1.11022302e-16  5.89805982e-17  1.38777878e-17]
753 ) -5 (0

860 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751707, 0.05941915432134204, -0.00467260925673782, 0.6067703912997695, -0.013822159161643185, -0.1918137704932571) [-6.24500451e-17  0.00000000e+00 -3.81639165e-17 -1.38777878e-17]
861 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751727, 0.05941915432134204, -0.004672609256737827, 0.6067703912997694, -0.013822159161643154, -0.19181377049325704) [-6.93889390e-18 -1.11022302e-16  3.12250226e-17  4.16333634e-17]
862 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751508, 0.05941915432134204, -0.00467260925673775, 0.6067703912997695, -0.013822159161643165, -0.19181377049325704) [ 7.63278329e-17  8.32667268e-17 -1.04083409e-17 -1.38777878e-17]
863 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751768, 0.05941915432134204, -0.0046726092567378405, 0.6067703912997695, -0.01382215916164323, -0.19181377049325704) [-9.02056208e-17  5.55111512e-17 -6.59194921e-17 -1.38777878e-17]
864

953 ) -5 (0.06820975046825362, 0.033474038803777695, -0.001192847367075165, 0.059419154321342135, -0.004672609256737799, 0.6067703912997693, -0.013822159161643085, -0.1918137704932572) [-6.24500451e-17 -8.32667268e-17  3.12250226e-17 -1.80411242e-16]
954 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751785, 0.059419154321341996, -0.0046726092567378474, 0.6067703912997695, -0.013822159161643137, -0.1918137704932572) [-4.85722573e-17  1.94289029e-16 -5.20417043e-17 -1.38777878e-17]
955 ) -5 (0.06820975046825345, 0.033474038803777584, -0.0011928473670752044, 0.059419154321341996, -0.004672609256737938, 0.6067703912997695, -0.013822159161643133, -0.1918137704932572) [-9.02056208e-17 -5.55111512e-17  3.46944695e-18  1.38777878e-17]
956 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751825, 0.059419154321341996, -0.004672609256737861, 0.6067703912997694, -0.013822159161643088, -0.19181377049325726) [ 7.63278329e-17 -8.32667268e-17  4.51028104e-17 -6.93889

1055 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075141, 0.05941915432134204, -0.004672609256737716, 0.6067703912997695, -0.013822159161643203, -0.19181377049325715) [ 2.15105711e-16 -2.77555756e-17 -3.81639165e-17  1.38777878e-17]
1056 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751749, 0.05941915432134204, -0.0046726092567378336, 0.6067703912997695, -0.013822159161643172, -0.19181377049325715) [-1.17961196e-16 -2.77555756e-17  3.12250226e-17  1.38777878e-17]
1057 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751768, 0.05941915432134204, -0.0046726092567378405, 0.6067703912997695, -0.013822159161643154, -0.1918137704932571) [-6.93889390e-18 -2.77555756e-17  1.73472348e-17  6.93889390e-17]
1058 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751707, 0.05941915432134204, -0.00467260925673782, 0.6067703912997695, -0.013822159161643137, -0.1918137704932571) [ 2.08166817e-17 -2.77555756e-17  1.73472348e-17  1.38777878e-17

1160 ) -5 (0.06820975046825344, 0.033474038803777584, -0.0011928473670751625, 0.059419154321341996, -0.004672609256737792, 0.6067703912997695, -0.013822159161643213, -0.19181377049325726) [ 1.17961196e-16 -1.11022302e-16 -7.97972799e-17 -9.71445147e-17]
1161 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752126, 0.05941915432134204, -0.004672609256737965, 0.6067703912997695, -0.013822159161643154, -0.19181377049325715) [-1.73472348e-16  2.77555756e-17  5.89805982e-17  9.71445147e-17]
1162 ) -5 (0.0682097504682535, 0.03347403880377764, -0.001192847367075155, 0.05941915432134204, -0.004672609256737764, 0.6067703912997694, -0.013822159161643068, -0.1918137704932571) [ 2.01227923e-16 -1.11022302e-16  8.67361738e-17  4.16333634e-17]
1163 ) -5 (0.06820975046825345, 0.033474038803777584, -0.0011928473670752124, 0.059419154321341996, -0.004672609256737965, 0.6067703912997694, -0.013822159161643161, -0.1918137704932572) [-2.01227923e-16  2.77555756e-17 -9.36750677e-17 -1.2490009

1263 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751768, 0.05941915432134204, -0.0046726092567378405, 0.6067703912997695, -0.01382215916164323, -0.19181377049325704) [-9.02056208e-17  5.55111512e-17 -6.59194921e-17 -1.38777878e-17]
1264 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670750753, 0.05941915432134204, -0.004672609256737487, 0.6067703912997695, -0.013822159161643255, -0.19181377049325699) [ 3.53883589e-16  0.00000000e+00 -2.42861287e-17  6.93889390e-17]
1265 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752126, 0.05941915432134204, -0.004672609256737965, 0.6067703912997695, -0.013822159161643376, -0.19181377049325704) [-4.78783679e-16  5.55111512e-17 -1.21430643e-16 -6.93889390e-17]
1266 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752384, 0.05941915432134204, -0.004672609256738056, 0.6067703912997695, -0.013822159161643248, -0.1918137704932571) [-9.02056208e-17 -5.55111512e-17  1.28369537e-16 -4.16333634e-1

1385 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752126, 0.05941915432134204, -0.004672609256737965, 0.6067703912997695, -0.013822159161643376, -0.19181377049325704) [-4.78783679e-16  5.55111512e-17 -1.21430643e-16 -6.93889390e-17]
1386 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752384, 0.05941915432134204, -0.004672609256738056, 0.6067703912997695, -0.013822159161643248, -0.1918137704932571) [-9.02056208e-17 -5.55111512e-17  1.28369537e-16 -4.16333634e-17]
1387 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670752007, 0.05941915432134204, -0.004672609256737924, 0.6067703912997694, -0.013822159161643147, -0.1918137704932571) [ 1.31838984e-16 -1.11022302e-16  1.00613962e-16 -1.38777878e-17]
1388 ) -5 (0.0682097504682535, 0.03347403880377764, -0.0011928473670751469, 0.05941915432134204, -0.004672609256737736, 0.6067703912997695, -0.013822159161643158, -0.19181377049325715) [ 1.87350135e-16  5.55111512e-17 -1.04083409e-17 -6.93889390e-17

KeyboardInterrupt: 

In [24]:
import numpy as np
env.state = np.zeros(4)
agent.play(env)

1 ) 0.010000000000000002 (0.05528517104369137, 0.03472558480673413, -0.006836836685538417, -0.04247165597543617, 0.34380847685091953, 0.32469959675299565, 0.0032804669517428886, -0.4684083863840015) [ 0.34380848  0.3246996   0.00328047 -0.46840839]
2 ) 100.009 (0.044856183029329914, 0.03240930405876355, -0.0019106631164287624, -0.030952601390559678, 0.3636359650110518, 0.2825948711187707, 0.0032804669517428886, -0.4684083863840015) [ 0.01982749 -0.04210473  0.03873927 -0.31883895]


In [4]:
env1 = gym.make("crumb-pick-v0")
#agent.grasp(env1)
#agent.pick(env1)
#agent.putdown(env1)

In [8]:
(0.4392827844092338, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, -1.5707963267948966, 1.5707963267948966, 0.3795212282445104, -1.5707963267948966)

(0.4392827844092338,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 -1.5707963267948966,
 1.5707963267948966,
 0.3795212282445104,
 -1.5707963267948966)

In [5]:
agent.grasp(env1)

1 ) 0.007000000000000006 (0.23, 0.2, 0.05, 0.07, 0.12, 0.78, 0.32, 0.39) [0.12797938 0.75730049 0.33070355 0.41555789]
2 ) 0.017999999999999988 (0.14, 0.11, 0.02, -0.03, 0.36, 1.2, 0.47000000000000003, 0.63) [0.23687681 0.40317045 0.1144163  0.20252017]
3 ) 0.011999999999999983 (0.15, 0.12, 0.0, -0.03, 0.35000000000000003, 1.34, 0.53, 0.88) [-0.01286168  0.17568968 -0.00823797  0.0606187 ]
4 ) 0.008000000000000007 (0.17, 0.14, -0.05, -0.03, 0.37, 1.46, 0.64, 1.04) [ 0.02067291  0.19924721 -0.09267958 -0.03955087]


KeyboardInterrupt: 

In [10]:
env1.arm[3].publish(0)

In [5]:
import numpy as np
def metric(a1, a2):
    return ((a1-a2)**2).sum()**(1/2)

def get_pose(joint):
    a = env1.link_state(joint, '').link_state.pose.position
    return np.array([a.x, a.y, a.z])

def length():
    length = np.zeros(4)
    joint = np.zeros((4,3))
    joint[0] = get_pose('biceps_link')
    joint[1] = get_pose('forearm_link')
    joint[2] = get_pose('wrist_1_link')
    joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2
    for i in range(3):
        length[i] = metric(joint[i+1], joint[i])
    return length

box, _ = env1.get_state()
box = np.array([box.x, box.y, box.z])
bic = get_pose('biceps_link')
bic - box

array([-0.05530484, -0.29997266,  0.11164202])

In [36]:
aim1 = np.array([env1.aim.x, env1.aim.y, env1.aim.z])
joint = np.zeros((4, 3))
joint[0] = get_pose('biceps_link')
joint[1] = get_pose('forearm_link')
joint[2] = get_pose('wrist_1_link')
joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2

# vectors
vec1 = np.zeros((3, 3))
vec2 = np.zeros((3, 3))

for i in range(3):
    vec1[i] = joint[3] - joint[i]
    vec2[i] = aim1 - joint[i]

In [6]:
length()

array([0.15000095, 0.14202985, 0.11453303, 0.        ])

In [38]:
vec2

array([[ 0.04790541,  0.43824102, -0.11164279],
       [ 0.04456551,  0.3906848 , -0.25386632],
       [ 0.03490639,  0.24898522, -0.25339561]])

In [39]:
vec1 - vec2

array([[-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619]])