In [1]:
import gym
import gym_crumb
from agent.agent_synth import AgentSynth

In [2]:
import matplotlib.pyplot as plt
import os
if os.environ.get("DISPLAY") is str and len(os.environ.get("DISPLAY"))!=0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [3]:
env = gym.make("crumb-synthetic-v0")
agent = AgentSynth(env)

WARN: Environment '<class 'gym_crumb.envs.crumb_synthetic_env.CrumbSyntheticEnv'>' has deprecated methods '_step' and '_reset' rather than 'step' and 'reset'. Compatibility code invoked. Set _gym_disable_underscore_compat = True to disable this behavior.


In [5]:
agent.net.Loadmodel()

In [4]:
rewards, i = agent.learn(reward=220, max_pathlength=5, n_timesteps=10000)


********** Iteration 1 ************
Rollout
Made rollout
Total number of episodes:                 2276
Average sum of rewards per episode:       -38.81811379613357
Std of rewards per episode:               32.209259242363764
Entropy:                                  -60074.681491459145
KL between old and new distribution:      0.009855100410141166
Surrogate loss:                           220678.1522239124

********** Iteration 2 ************
Rollout


KeyboardInterrupt: 

In [25]:
agent.net.Savemodel()

In [6]:
import numpy as np
env.state = np.zeros(4)
agent.play(env)

1 ) 100.165 (0.04207308277416921, -0.009627722253900628, -0.008232780179452545, 0.04012072517839943, 0.2073022843183901, 0.542460988600035, 0.0, 0.0) [ 0.20730228  0.54246099  0.22534633 -0.34063917]


In [4]:
env1 = gym.make("crumb-pick-v0")
#agent.grasp(env1)
#agent.pick(env1)
#agent.putdown(env1)

In [8]:
(0.4392827844092338, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, -1.5707963267948966, 1.5707963267948966, 0.3795212282445104, -1.5707963267948966)

(0.4392827844092338,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 -1.5707963267948966,
 1.5707963267948966,
 0.3795212282445104,
 -1.5707963267948966)

In [5]:
agent.grasp(env1)

1 ) 0.007000000000000006 (0.23, 0.2, 0.05, 0.07, 0.12, 0.78, 0.32, 0.39) [0.12797938 0.75730049 0.33070355 0.41555789]
2 ) 0.017999999999999988 (0.14, 0.11, 0.02, -0.03, 0.36, 1.2, 0.47000000000000003, 0.63) [0.23687681 0.40317045 0.1144163  0.20252017]
3 ) 0.011999999999999983 (0.15, 0.12, 0.0, -0.03, 0.35000000000000003, 1.34, 0.53, 0.88) [-0.01286168  0.17568968 -0.00823797  0.0606187 ]
4 ) 0.008000000000000007 (0.17, 0.14, -0.05, -0.03, 0.37, 1.46, 0.64, 1.04) [ 0.02067291  0.19924721 -0.09267958 -0.03955087]


KeyboardInterrupt: 

In [10]:
env1.arm[3].publish(0)

In [5]:
import numpy as np
def metric(a1, a2):
    return ((a1-a2)**2).sum()**(1/2)

def get_pose(joint):
    a = env1.link_state(joint, '').link_state.pose.position
    return np.array([a.x, a.y, a.z])

def length():
    length = np.zeros(4)
    joint = np.zeros((4,3))
    joint[0] = get_pose('biceps_link')
    joint[1] = get_pose('forearm_link')
    joint[2] = get_pose('wrist_1_link')
    joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2
    for i in range(3):
        length[i] = metric(joint[i+1], joint[i])
    return length

box, _ = env1.get_state()
box = np.array([box.x, box.y, box.z])
bic = get_pose('biceps_link')
bic - box

array([-0.05530484, -0.29997266,  0.11164202])

In [36]:
aim1 = np.array([env1.aim.x, env1.aim.y, env1.aim.z])
joint = np.zeros((4, 3))
joint[0] = get_pose('biceps_link')
joint[1] = get_pose('forearm_link')
joint[2] = get_pose('wrist_1_link')
joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2

# vectors
vec1 = np.zeros((3, 3))
vec2 = np.zeros((3, 3))

for i in range(3):
    vec1[i] = joint[3] - joint[i]
    vec2[i] = aim1 - joint[i]

In [6]:
length()

array([0.15000095, 0.14202985, 0.11453303, 0.        ])

In [38]:
vec2

array([[ 0.04790541,  0.43824102, -0.11164279],
       [ 0.04456551,  0.3906848 , -0.25386632],
       [ 0.03490639,  0.24898522, -0.25339561]])

In [39]:
vec1 - vec2

array([[-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619]])