In [1]:
import gym
import gym_crumb
from agent.agent_TRPO import TRPOAgent

In [3]:
import matplotlib.pyplot as plt
import os
if os.environ.get("DISPLAY") is str and len(os.environ.get("DISPLAY"))!=0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [5]:
env = gym.make("crumb-synthetic-v0")
agent = TRPOAgent(env)
#agent.net.Loadmodel()

In [13]:
rewards, i = agent.learn(reward=150, max_pathlength=5, n_timesteps=5000)


********** Iteration 1 ************
Rollout
Made rollout
Total number of episodes:                 1255
Average sum of rewards per episode:       94.02505258964143
Std of rewards per episode:               125.24830336309664
Entropy:                                  -11119.668806582855
KL between old and new distribution:      0.009931345692464257
Surrogate loss:                           -283685.1429624296

********** Iteration 2 ************
Rollout
Made rollout
Total number of episodes:                 1240
Average sum of rewards per episode:       93.56098629032259
Std of rewards per episode:               123.58861643756771
Entropy:                                  -11175.854088308686
KL between old and new distribution:      0.00985592034791564
Surrogate loss:                           -273549.88709997776

********** Iteration 3 ************
Rollout
Made rollout
Total number of episodes:                 1258
Average sum of rewards per episode:       99.71114864864865
Std of rewa

Made rollout
Total number of episodes:                 1440
Average sum of rewards per episode:       140.39744166666665
Std of rewards per episode:               132.65424385051597
Entropy:                                  -7928.074477594016
KL between old and new distribution:      0.009936475868854478
Surrogate loss:                           -445866.37688058603

********** Iteration 22 ************
Rollout
Made rollout
Total number of episodes:                 1397
Average sum of rewards per episode:       139.20014674302075
Std of rewards per episode:               134.16478563359857
Entropy:                                  -7786.770968221724
KL between old and new distribution:      0.00988571963766268
Surrogate loss:                           -445204.9876274656

********** Iteration 23 ************
Rollout
Made rollout
Total number of episodes:                 1428
Average sum of rewards per episode:       144.820100140056
Std of rewards per episode:               140.587245743

In [14]:
agent.net.Savemodel()

In [17]:
agent.play(env)

1 ) 100.008 (0.043555775121174554, 0.001407552054996014, 0.04093742568242831, 0.014807144293025029, -0.2912763527358712, 1.4005109685912707, 0.7003307579702631, 1.3456062475206525) [-0.01299617  0.04960444 -0.06707758  0.27983246]


In [4]:
env1 = gym.make("crumb-pick-v0")
#agent.grasp(env1)
#agent.pick(env1)
#agent.putdown(env1)

In [8]:
(0.4392827844092338, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, -1.5707963267948966, 1.5707963267948966, 0.3795212282445104, -1.5707963267948966)

(0.4392827844092338,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 -1.5707963267948966,
 1.5707963267948966,
 0.3795212282445104,
 -1.5707963267948966)

In [5]:
agent.grasp(env1)

1 ) 0.007000000000000006 (0.23, 0.2, 0.05, 0.07, 0.12, 0.78, 0.32, 0.39) [0.12797938 0.75730049 0.33070355 0.41555789]
2 ) 0.017999999999999988 (0.14, 0.11, 0.02, -0.03, 0.36, 1.2, 0.47000000000000003, 0.63) [0.23687681 0.40317045 0.1144163  0.20252017]
3 ) 0.011999999999999983 (0.15, 0.12, 0.0, -0.03, 0.35000000000000003, 1.34, 0.53, 0.88) [-0.01286168  0.17568968 -0.00823797  0.0606187 ]
4 ) 0.008000000000000007 (0.17, 0.14, -0.05, -0.03, 0.37, 1.46, 0.64, 1.04) [ 0.02067291  0.19924721 -0.09267958 -0.03955087]


KeyboardInterrupt: 

In [10]:
env1.arm[3].publish(0)

In [5]:
import numpy as np
def metric(a1, a2):
    return ((a1-a2)**2).sum()**(1/2)

def get_pose(joint):
    a = env1.link_state(joint, '').link_state.pose.position
    return np.array([a.x, a.y, a.z])

def length():
    length = np.zeros(4)
    joint = np.zeros((4,3))
    joint[0] = get_pose('biceps_link')
    joint[1] = get_pose('forearm_link')
    joint[2] = get_pose('wrist_1_link')
    joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2
    for i in range(3):
        length[i] = metric(joint[i+1], joint[i])
    return length

box, _ = env1.get_state()
box = np.array([box.x, box.y, box.z])
bic = get_pose('biceps_link')
bic - box

array([-0.05530484, -0.29997266,  0.11164202])

In [36]:
aim1 = np.array([env1.aim.x, env1.aim.y, env1.aim.z])
joint = np.zeros((4, 3))
joint[0] = get_pose('biceps_link')
joint[1] = get_pose('forearm_link')
joint[2] = get_pose('wrist_1_link')
joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2

# vectors
vec1 = np.zeros((3, 3))
vec2 = np.zeros((3, 3))

for i in range(3):
    vec1[i] = joint[3] - joint[i]
    vec2[i] = aim1 - joint[i]

In [6]:
length()

array([0.15000095, 0.14202985, 0.11453303, 0.        ])

In [38]:
vec2

array([[ 0.04790541,  0.43824102, -0.11164279],
       [ 0.04456551,  0.3906848 , -0.25386632],
       [ 0.03490639,  0.24898522, -0.25339561]])

In [39]:
vec1 - vec2

array([[-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619]])