In [1]:
import gym
import gym_crumb
from agent.agent_TRPO import TRPOAgent

In [2]:
import matplotlib.pyplot as plt
import os
if os.environ.get("DISPLAY") is str and len(os.environ.get("DISPLAY"))!=0:
    !bash ../xvfb start
    %env DISPLAY=:1

In [3]:
env = gym.make("crumb-synthetic-v0")
agent = TRPOAgent(env)
#agent.net.Loadmodel()

In [4]:
rewards, i = agent.learn(reward=100, max_pathlength=5, n_timesteps=10000)


********** Iteration 1 ************
Rollout
Made rollout
Total number of episodes:                 2043
Average sum of rewards per episode:       -50.8613641703
Std of rewards per episode:               56.9045915139
Entropy:                                  -60872.218777948474
KL between old and new distribution:      0.00994523350393292
Surrogate loss:                           254222.46390111206

********** Iteration 2 ************
Rollout
Made rollout
Total number of episodes:                 2042
Average sum of rewards per episode:       -48.3803109696
Std of rewards per episode:               55.6604659154
Entropy:                                  -60709.83942483559
KL between old and new distribution:      0.009960627742706635
Surrogate loss:                           243922.2528730768

********** Iteration 3 ************
Rollout
Made rollout
Total number of episodes:                 2046
Average sum of rewards per episode:       -47.3466212121
Std of rewards per episode:      

Made rollout
Total number of episodes:                 2007
Average sum of rewards per episode:       -24.5130901844
Std of rewards per episode:               25.6543898738
Entropy:                                  -56717.3573558682
KL between old and new distribution:      0.009895241198635054
Surrogate loss:                           125985.73550402894

********** Iteration 23 ************
Rollout
Made rollout
Total number of episodes:                 2012
Average sum of rewards per episode:       -24.2337117296
Std of rewards per episode:               23.0985147638
Entropy:                                  -56576.1350066138
KL between old and new distribution:      0.009935015756541807
Surrogate loss:                           124602.53042155883

********** Iteration 24 ************
Rollout
Made rollout
Total number of episodes:                 2003
Average sum of rewards per episode:       -23.2449375936
Std of rewards per episode:               25.0099957492
Entropy:             

Made rollout
Total number of episodes:                 2003
Average sum of rewards per episode:       -19.6380104843
Std of rewards per episode:               22.1677552444
Entropy:                                  -52557.90078787407
KL between old and new distribution:      0.00992658319543644
Surrogate loss:                           99184.6269270361

********** Iteration 44 ************
Rollout
Made rollout
Total number of episodes:                 2002
Average sum of rewards per episode:       -18.116046953
Std of rewards per episode:               20.1040031037
Entropy:                                  -52306.61431870306
KL between old and new distribution:      0.009909618290610598
Surrogate loss:                           93986.58187071011

********** Iteration 45 ************
Rollout
Made rollout
Total number of episodes:                 2004
Average sum of rewards per episode:       -18.2024076846
Std of rewards per episode:               18.4260044391
Entropy:                

Made rollout
Total number of episodes:                 2003
Average sum of rewards per episode:       -13.6676969546
Std of rewards per episode:               18.1502827856
Entropy:                                  -48172.18309970641
KL between old and new distribution:      0.00986285082408722
Surrogate loss:                           69844.91761134323

********** Iteration 65 ************
Rollout
Made rollout
Total number of episodes:                 2003
Average sum of rewards per episode:       -14.0129410884
Std of rewards per episode:               15.6040258366
Entropy:                                  -47939.650454603565
KL between old and new distribution:      0.009984125555292465
Surrogate loss:                           72626.87802346973

********** Iteration 66 ************
Rollout
Made rollout
Total number of episodes:                 2005
Average sum of rewards per episode:       -13.4496399002
Std of rewards per episode:               18.9312692994
Entropy:             

Made rollout
Total number of episodes:                 2002
Average sum of rewards per episode:       -10.1707767233
Std of rewards per episode:               17.6564405456
Entropy:                                  -43694.255962227995
KL between old and new distribution:      0.009963055668808648
Surrogate loss:                           51330.012945912305

********** Iteration 86 ************
Rollout
Made rollout
Total number of episodes:                 2003
Average sum of rewards per episode:       -9.72942436345
Std of rewards per episode:               15.3535162399
Entropy:                                  -43493.59099408027
KL between old and new distribution:      0.009969999370693561
Surrogate loss:                           48944.951370401104

********** Iteration 87 ************
Rollout
Made rollout
Total number of episodes:                 2005
Average sum of rewards per episode:       -9.76521845387
Std of rewards per episode:               15.9712301686
Entropy:          

Made rollout
Total number of episodes:                 2006
Average sum of rewards per episode:       -6.41796410768
Std of rewards per episode:               15.980497387
Entropy:                                  -39399.51448911441
KL between old and new distribution:      0.009978243822732253
Surrogate loss:                           34642.75555124794

********** Iteration 107 ************
Rollout
Made rollout
Total number of episodes:                 2009
Average sum of rewards per episode:       -6.09159930314
Std of rewards per episode:               16.8337068494
Entropy:                                  -39098.90225760316
KL between old and new distribution:      0.009841983722451672
Surrogate loss:                           33976.77779059342

********** Iteration 108 ************
Rollout
Made rollout
Total number of episodes:                 2005
Average sum of rewards per episode:       -6.1283042394
Std of rewards per episode:               13.6807490082
Entropy:             

Made rollout
Total number of episodes:                 2005
Average sum of rewards per episode:       -3.79579551122
Std of rewards per episode:               17.2877912548
Entropy:                                  -35190.830385393114
KL between old and new distribution:      0.009957917834829421
Surrogate loss:                           22708.56568561142

********** Iteration 128 ************
Rollout
Made rollout
Total number of episodes:                 2004
Average sum of rewards per episode:       -4.5430508982
Std of rewards per episode:               13.6076464251
Entropy:                                  -34923.63184713021
KL between old and new distribution:      0.009937622607029984
Surrogate loss:                           23761.75355400991

********** Iteration 129 ************
Rollout
Made rollout
Total number of episodes:                 2007
Average sum of rewards per episode:       -4.43707274539
Std of rewards per episode:               15.6794328779
Entropy:           

Made rollout
Total number of episodes:                 2008
Average sum of rewards per episode:       -3.37041384462
Std of rewards per episode:               17.0472319695
Entropy:                                  -31364.552306433343
KL between old and new distribution:      0.009939908889371487
Surrogate loss:                           16913.554614732824

********** Iteration 149 ************
Rollout
Made rollout
Total number of episodes:                 2005
Average sum of rewards per episode:       -2.80108229426
Std of rewards per episode:               17.8805336667
Entropy:                                  -31165.082903136983
KL between old and new distribution:      0.009900981692737445
Surrogate loss:                           13770.007573171864

********** Iteration 150 ************
Rollout
Made rollout
Total number of episodes:                 2008
Average sum of rewards per episode:       -3.05206324701
Std of rewards per episode:               16.7983678657
Entropy:       

Made rollout
Total number of episodes:                 2021
Average sum of rewards per episode:       0.403199406235
Std of rewards per episode:               27.7802582175
Entropy:                                  -27747.3528415875
KL between old and new distribution:      0.009965296610898386
Surrogate loss:                           -2017.7990206827265

********** Iteration 170 ************
Rollout
Made rollout
Total number of episodes:                 2018
Average sum of rewards per episode:       0.795729435084
Std of rewards per episode:               31.6787991423
Entropy:                                  -27450.062472704427
KL between old and new distribution:      0.009948582746191382
Surrogate loss:                           -5021.153549706828

********** Iteration 171 ************
Rollout
Made rollout
Total number of episodes:                 2023
Average sum of rewards per episode:       1.25647305981
Std of rewards per episode:               31.2961371873
Entropy:         

Made rollout
Total number of episodes:                 2116
Average sum of rewards per episode:       19.181289225
Std of rewards per episode:               70.6864909722
Entropy:                                  -20381.036916103483
KL between old and new distribution:      0.009938423201841875
Surrogate loss:                           -107034.62450071599

********** Iteration 191 ************
Rollout
Made rollout
Total number of episodes:                 2128
Average sum of rewards per episode:       22.7232091165
Std of rewards per episode:               72.7541042688
Entropy:                                  -19518.93478701595
KL between old and new distribution:      0.009875859238125369
Surrogate loss:                           -129575.2346532816

********** Iteration 192 ************
Rollout
Made rollout
Total number of episodes:                 2122
Average sum of rewards per episode:       22.0272492931
Std of rewards per episode:               71.303551541
Entropy:            

Made rollout
Total number of episodes:                 2286
Average sum of rewards per episode:       57.0289728784
Std of rewards per episode:               107.789319973
Entropy:                                  -9553.70914194577
KL between old and new distribution:      0.009848191527230276
Surrogate loss:                           -334735.9959646073

********** Iteration 212 ************
Rollout
Made rollout
Total number of episodes:                 2288
Average sum of rewards per episode:       58.3701822552
Std of rewards per episode:               111.190523239
Entropy:                                  -9465.027461261789
KL between old and new distribution:      0.009881591360697854
Surrogate loss:                           -352095.05328615295

********** Iteration 213 ************
Rollout
Made rollout
Total number of episodes:                 2289
Average sum of rewards per episode:       55.2756168633
Std of rewards per episode:               106.44642251
Entropy:             

Made rollout
Total number of episodes:                 2573
Average sum of rewards per episode:       98.4296572095
Std of rewards per episode:               134.652800809
Entropy:                                  -1127.6429704293791
KL between old and new distribution:      0.00993119318591915
Surrogate loss:                           -635043.7726918076

********** Iteration 233 ************
Rollout
Made rollout


In [19]:
agent.net.Savemodel()

In [8]:
import numpy as np
env.state = np.zeros(4)
agent.play(env)

1 ) 0.007 (0.069819509806770153, -0.017916590873314819, -0.062569357573549922, 0.025275189692051322, 0.48370953749318285, 0.32382429822878689, 0.14117034484180541, -0.17979102532712815) [ 0.48370954  0.3238243   0.14117034 -0.17979103]
2 ) 100.02 (0.045582557624537938, -0.0040314712451071655, -0.044320371136516434, -0.0098600964252707132, 0.51357823720325491, 0.53002662320452265, 0.25890983035298876, -0.17979102532712815) [ 0.0298687   0.20620232  0.11773949 -0.13491525]


In [4]:
env1 = gym.make("crumb-pick-v0")
#agent.grasp(env1)
#agent.pick(env1)
#agent.putdown(env1)

In [8]:
(0.4392827844092338, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, 0.2695451879616264, -0.34615669, 0.022142770678141632, -1.5707963267948966, 1.5707963267948966, 0.3795212282445104, -1.5707963267948966)

(0.4392827844092338,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 0.2695451879616264,
 -0.34615669,
 0.022142770678141632,
 -1.5707963267948966,
 1.5707963267948966,
 0.3795212282445104,
 -1.5707963267948966)

In [5]:
agent.grasp(env1)

1 ) 0.007000000000000006 (0.23, 0.2, 0.05, 0.07, 0.12, 0.78, 0.32, 0.39) [0.12797938 0.75730049 0.33070355 0.41555789]
2 ) 0.017999999999999988 (0.14, 0.11, 0.02, -0.03, 0.36, 1.2, 0.47000000000000003, 0.63) [0.23687681 0.40317045 0.1144163  0.20252017]
3 ) 0.011999999999999983 (0.15, 0.12, 0.0, -0.03, 0.35000000000000003, 1.34, 0.53, 0.88) [-0.01286168  0.17568968 -0.00823797  0.0606187 ]
4 ) 0.008000000000000007 (0.17, 0.14, -0.05, -0.03, 0.37, 1.46, 0.64, 1.04) [ 0.02067291  0.19924721 -0.09267958 -0.03955087]


KeyboardInterrupt: 

In [10]:
env1.arm[3].publish(0)

In [5]:
import numpy as np
def metric(a1, a2):
    return ((a1-a2)**2).sum()**(1/2)

def get_pose(joint):
    a = env1.link_state(joint, '').link_state.pose.position
    return np.array([a.x, a.y, a.z])

def length():
    length = np.zeros(4)
    joint = np.zeros((4,3))
    joint[0] = get_pose('biceps_link')
    joint[1] = get_pose('forearm_link')
    joint[2] = get_pose('wrist_1_link')
    joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2
    for i in range(3):
        length[i] = metric(joint[i+1], joint[i])
    return length

box, _ = env1.get_state()
box = np.array([box.x, box.y, box.z])
bic = get_pose('biceps_link')
bic - box

array([-0.05530484, -0.29997266,  0.11164202])

In [36]:
aim1 = np.array([env1.aim.x, env1.aim.y, env1.aim.z])
joint = np.zeros((4, 3))
joint[0] = get_pose('biceps_link')
joint[1] = get_pose('forearm_link')
joint[2] = get_pose('wrist_1_link')
joint[3] = get_pose('gripper_1_link')/2 + get_pose('gripper_2_link')/2

# vectors
vec1 = np.zeros((3, 3))
vec2 = np.zeros((3, 3))

for i in range(3):
    vec1[i] = joint[3] - joint[i]
    vec2[i] = aim1 - joint[i]

In [6]:
length()

array([0.15000095, 0.14202985, 0.11453303, 0.        ])

In [38]:
vec2

array([[ 0.04790541,  0.43824102, -0.11164279],
       [ 0.04456551,  0.3906848 , -0.25386632],
       [ 0.03490639,  0.24898522, -0.25339561]])

In [39]:
vec1 - vec2

array([[-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619],
       [-0.03635168, -0.13413006,  0.25199619]])